### ISSUE TITLE
RIcochet eats 100% cpu when #271 triggers

### ISSUE THREAD

**Issue by armadev** [ricochet-im/ricochet#272]
Once I did the events that caused #271, my ricochet was eating 100% cpu. I attached a gdb and the stack trace on the interesting thread was:

```
Thread 1 (Thread 0x7f202977d840 (LWP 12684)):
#0  0x00007f2028725a08 in ?? () from /usr/lib/x86_64-linux-gnu/libasan.so.1
#1  0x00007f202871c322 in __asan_region_is_poisoned ()
   from /usr/lib/x86_64-linux-gnu/libasan.so.1
#2  0x00007f202870153c in pthread_cond_broadcast ()
   from /usr/lib/x86_64-linux-gnu/libasan.so.1
#3  0x00007f2023748df2 in ?? () from /usr/lib/x86_64-linux-gnu/libX11.so.6
#4  0x00007f2023748877 in XUnlockDisplay ()
   from /usr/lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007f2018cd5273 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#6  0x00007f2018cd657b in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#7  0x00007f20259b7eda in QObject::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f20269bc12c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007f20269c1600 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007f2025987dcb in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007f2025989dc3 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#12 0x00007f20259dfda3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f2023aa4c5d in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f2023aa4f48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f2023aa4ffc in g_main_context_iteration ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f20259e01b7 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007f2025985512 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f202598d15c in QCoreApplication::exec() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f20297e0e2c in main ()
```

**Comment by special** [comment]
There are other reports of this under Subgraph, particularly after the network goes down. Something in the tor control reconnection might not be throttling properly.
