### ISSUE TITLE
segfault when closing ricochet via window manager

### ISSUE THREAD

**Issue by infinity0** [ricochet-im/ricochet#410]
Forwarding from https://bugs.debian.org/819441, feel free to reply either here or to the OP if you need to ask them questions (be sure to CC 819441@bugs.debian.org in that case).

~~~~
Package: ricochet-im
Version: 1.1.2-1
Severity: normal

I launched ricochet.  I have one contact, who is online.

i used my window manager to close the ricochet window, and i got a
segmentation fault, rather than a clean shutdown.

after installing ricochet-dbgsym and libasan2-dbg, i repeated the
process, and got a segfault again.  it appears to be repeatable.

here's the backtrace i'm seeing:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000000010 in ?? ()
(gdb) bt
#0  0x0000000000000010 in  ()
#1  0x00007ffff6f1db53 in __sanitizer::LibbacktraceSymbolizer::SymbolizeCode(unsigned long, __sanitizer::AddressInfo*, unsigned long, char const*, unsigned long) (this=0x7fffe64ec000, addr=addr@entry=140737336335370, frames=frames@entry=0x7fffe64eb000, max_frames=max_frames@entry=16, module_name=module_name@entry=0x7fffe6500ba8 "/usr/lib/x86_64-linux-gnu/libasan.so.2", module_offset=module_offset@entry=609290)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_symbolizer_libbacktrace.cc:160
#2  0x00007ffff6f1f6c9 in __sanitizer::POSIXSymbolizer::SymbolizePC(unsigned long, __sanitizer::AddressInfo*, unsigned long) (this=0x7fffe64ec008, addr=140737336335370, frames=0x7fffe64eb000, max_frames=16)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_symbolizer_posix_libcdep.cc:527
#3  0x00007ffff6f22cad in __lsan::LeakReport::ApplySuppressions() (addr=140737336335370) at ../../../../src/libsanitizer/lsan/lsan_common.cc:473
#4  0x00007ffff6f22cad in __lsan::LeakReport::ApplySuppressions() (stack_trace_id=<optimized out>) at ../../../../src/libsanitizer/lsan/lsan_common.cc:488
#5  0x00007ffff6f22cad in __lsan::LeakReport::ApplySuppressions() (this=this@entry=0x7fffffffe0b8) at ../../../../src/libsanitizer/lsan/lsan_common.cc:603
#6  0x00007ffff6f23542 in __lsan::DoLeakCheck() ()
    at ../../../../src/libsanitizer/lsan/lsan_common.cc:433
#7  0x00007ffff2f5116f in __cxa_finalize (d=0x7ffff7165350)
    at cxa_finalize.c:56
#8  0x00007ffff6e8e473 in __do_global_dtors_aux ()
   libasan.so.2
#9  0x00007fffffffe4f0 in  ()
#10 0x00007ffff7dea8c7 in _dl_fini () at dl-fini.c:252
(gdb) 

Sorry to not be able to debug it further.

      --dkg

-- System Information:
Debian Release: stretch/sid
  APT prefers unstable-debug
  APT policy: (500, 'unstable-debug'), (500, 'testing'), (200, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.4.0-1-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_US.UTF-8, LC_CTYPE=en_US.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages ricochet-im depends on:
ii  libasan2                     5.3.1-12
ii  libc6                        2.22-3
ii  libgcc1                      1:5.3.1-12
ii  libgl1-mesa-glx [libgl1]     11.1.2-1
ii  libprotobuf9v5               2.6.1-1.3
ii  libqt5core5a                 5.5.1+dfsg-16
ii  libqt5gui5                   5.5.1+dfsg-16
ii  libqt5multimedia5            5.5.1-4
ii  libqt5network5               5.5.1+dfsg-16
ii  libqt5qml5                   5.5.1-3
ii  libqt5quick5                 5.5.1-3
ii  libqt5widgets5               5.5.1+dfsg-16
ii  libssl1.0.2                  1.0.2g-1
ii  libstdc++6                   5.3.1-12
ii  libubsan0                    5.3.1-12
ii  qml-module-qtmultimedia      5.5.1-4
ii  qml-module-qtquick-controls  5.5.1-2
ii  qml-module-qtquick-dialogs   5.5.1-2
ii  tor                          0.2.7.6-1

ricochet-im recommends no packages.

ricochet-im suggests no packages.

-- debconf-show failed
~~~~

**Comment by special** [comment]
We're not using ASAN for release builds anymore (#341), so crashes under ASAN's leak checker aren't relevant.

Why ASAN is crashing when trying to build a backtrace is an interesting question, but there's no reason to think it's indicating a Ricochet bug here.
